#!/usr/bin/env python3
"""Render the checked-in extension capability reference deterministically."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
MANIFEST_DIRECTORY = ROOT / "examples" / "extensions"
OUTPUT = ROOT / "docs" / "extension-capabilities.md"


def render() -> str:
    rows: list[tuple[str, str, str, str, str, str]] = []
    for path in sorted(MANIFEST_DIRECTORY.glob("*.manifest.json")):
        manifest = json.loads(path.read_text(encoding="utf-8"))
        for capability in manifest["capabilities"]:
            rows.append(
                (
                    manifest["extension_id"],
                    manifest["version"],
                    capability["capability_id"],
                    capability["kind"],
                    capability["determinism"],
                    capability["coverage"]["mode"],
                )
            )
    lines = [
        "# Extension capability reference",
        "",
        "<!-- Generated by scripts/generate-extension-docs.py; do not edit by hand. -->",
        "",
        "This table is generated from the checked-in, contract-valid reference manifests.",
        "",
        "| Extension | Version | Capability | Role | Determinism | Declared coverage |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    lines.extend(
        [
            "",
            "The supported host contract is `optiflow.extension-sdk.v1`. Provider availability also depends on an exact manifest digest, an operator-owned lock, compatible configuration evidence, effect grants, and unique precedence.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    if arguments.check == arguments.write:
        parser.error("select exactly one of --check or --write")
    rendered = render()
    if arguments.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        return 0
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
        print("extension capability reference is stale; run with --write", flush=True)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
